mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

share_the_starry_sky/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('mainapp/', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('',  RedirectView.as_view(url='/mainapp/')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.urls import reverse

class Submissions(models.Model):
    username = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')
    comment = models.TextField()

    def get_absolute_url(self):
        return reverse('mainapp:detail', kwargs={'pk': self.pk})

class Exif(models.Model):
    submission = models.OneToOneField(Submissions, on_delete=models.CASCADE, related_name="exif_data", null=True)
    aperture_value = models.FloatField(blank=True, null=True)
    brightness_value = models.FloatField(blank=True, null=True)
    date_time_original = models.DateTimeField(blank=True, null=True)
    exposure_bias_value = models.FloatField(blank=True, null=True)
    exposure_program = models.IntegerField(blank=True, null=True)
    exposure_time = models.FloatField(blank=True, null=True)
    f_number = models.FloatField(blank=True, null=True)
    iso = models.IntegerField(blank=True, null=True)
    max_aperture_value = models.FloatField(blank=True, null=True)
    metering_mode = models.IntegerField(blank=True, null=True)
    shutter_speed_value = models.FloatField(blank=True, null=True)

    gps_altitude = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    gps_altitude_ref = models.IntegerField(blank=True, null=True)
    gps_latitude = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    gps_latitude_ref = models.CharField(max_length=1, blank=True, null=True)
    gps_longitude = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    gps_longitude_ref = models.CharField(max_length=1, blank=True, null=True)

    make = models.CharField(max_length=255, blank=True, null=True)
    model = models.CharField(max_length=255, blank=True, null=True)
    lens_make = models.CharField(max_length=255, blank=True, null=True)
    lens_model = models.CharField(max_length=255, blank=True, null=True)

    exposure_time_star = models.FloatField(blank=True, null=True)
    f_number_star = models.FloatField(blank=True, null=True)
    iso_star = models.IntegerField(blank=True, null=True)
    focal_length_star = models.FloatField(blank=True, null=True)

mainapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Submissions, Exif
from PIL import Image, ExifTags
from django.core.files import File
import io
from datetime import datetime
from PIL.ExifTags import TAGS, GPSTAGS
from fractions import Fraction
import decimal

# def get_decimal_from_dms(dms, ref):
#     degrees, minutes, seconds = [float(val.numerator) / float(val.denominator) for val in dms]
#     result = degrees + (minutes / 60.0) + (seconds / 3600.0)
#     if ref in ['S', 'W']:
#         result *= -1
#     return result

# def get_decimal_from_dms_altitude(dms, ref):
#     result = float(dms.numerator) / float(dms.denominator)
#     if ref == 1:
#         result *= -1
#     return result

# def get_exif_data(image):
#     raw_exif_data = image._getexif()
#     exif_data = {}
#     if raw_exif_data is not None:
#         for tag, value in raw_exif_data.items():
#             tag_name = TAGS.get(tag, tag)
#             if tag_name == 'DateTimeOriginal':
#                 exif_data[tag_name] = datetime.strptime(value, '%Y:%m:%d %H:%M:%S')
#             elif tag_name in ['GPSLatitude', 'GPSLongitude']:
#                 ref = raw_exif_data.get(GPSTAGS.get(tag+1))  # 'N', 'S', 'E', 'W'
#                 exif_data[tag_name] = get_decimal_from_dms(value, ref)
#             elif tag_name == 'GPSAltitude':
#                 ref = raw_exif_data.get(GPSTAGS.get(tag+1))  # 0, 1
#                 exif_data[tag_name] = get_decimal_from_dms_altitude(value, ref)
#             elif isinstance(value, bytes):
#                 exif_data[tag_name] = value.decode('utf-8', 'ignore')
#             else:
#                 exif_data[tag_name] = value
#     return exif_data

def get_decimal_from_dms(dms, ref):
    # If the input is already in degrees format, just return it
    if isinstance(dms, (int, float)):
        result = float(dms)
    else:
        # Otherwise, convert from DMS (Degree/Minute/Second) to decimal format
        degrees, minutes, seconds = [float(val.numerator) / float(val.denominator) for val in dms]
        result = degrees + (minutes / 60.0) + (seconds / 3600.0)
    
    if ref in ['S', 'W']:
        result *= -1

    # Round to 3 decimal places
    result = round(result, 3)
    
    return result


def get_decimal_from_dms_altitude(dms, ref):
    # If the input is already in degrees format, just return it
    if isinstance(dms, (int, float)):
        result = float(dms)
    else:
        # Otherwise, convert from DMS (Degree/Minute/Second) to decimal format
        result = float(dms.numerator) / float(dms.denominator)
    
    if ref == 1:
        result *= -1

    # Round to 3 decimal places
    result = round(result, 3)
    
    return result


def get_exif_data(image):
    raw_exif_data = image._getexif()
    exif_data = {}
    if raw_exif_data is not None:
        for tag, value in raw_exif_data.items():
            tag_name = ExifTags.TAGS.get(tag, tag)
            if tag_name == 'DateTimeOriginal':
                exif_data[tag_name] = datetime.strptime(value, '%Y:%m:%d %H:%M:%S')
            elif tag_name == 'GPSInfo':
                for t, val in value.items():
                    subtag_name = ExifTags.GPSTAGS.get(t, t)
                    if subtag_name in ['GPSLatitude', 'GPSLongitude']:
                        ref = value.get(1 if subtag_name == 'GPSLatitude' else 3)  # 'N', 'S', 'E', 'W'
                        exif_data[subtag_name] = get_decimal_from_dms(val, ref)
                    elif subtag_name == 'GPSAltitude':
                        ref = int.from_bytes(value.get(5), byteorder='big')  # 0, 1
                        exif_data[subtag_name] = get_decimal_from_dms_altitude(val, ref)
                        exif_data['GPSAltitudeRef'] = ref
                    else:
                        exif_data[subtag_name] = val
            elif isinstance(value, bytes):
                exif_data[tag_name] = value.decode('utf-8', 'ignore')
            else:
                exif_data[tag_name] = value
    return exif_data



class IndexView(generic.ListView):
    model = Submissions
    paginate_by = 5

class DetailView(generic.DetailView):
    model = Submissions

# class CreateView(generic.edit.CreateView):
#     model = Submissions
#     fields = '__all__'

# class UpdateView(generic.edit.UpdateView):
#     model = Submissions
#     fields = '__all__'

class DeleteView(generic.edit.DeleteView):
    model = Submissions
    success_url = reverse_lazy('mainapp:index')


class CreateView(generic.edit.CreateView):
    model = Submissions
    fields = '__all__'

    def form_valid(self, form):
        self.object = form.save()
        with Image.open(self.object.image.path) as img:
            exif_data = get_exif_data(img)
            if exif_data is not None:
                Exif.objects.create(
                    submission=self.object,
                    aperture_value=exif_data.get('ApertureValue'),
                    brightness_value=exif_data.get('BrightnessValue'),
                    date_time_original=exif_data.get('DateTimeOriginal'),
                    exposure_bias_value=exif_data.get('ExposureBiasValue'),
                    exposure_program=exif_data.get('ExposureProgram'),
                    exposure_time=exif_data.get('ExposureTime'),
                    f_number=exif_data.get('FNumber'),
                    iso=exif_data.get('ISOSpeedRatings'),
                    max_aperture_value=exif_data.get('MaxApertureValue'),
                    metering_mode=exif_data.get('MeteringMode'),
                    shutter_speed_value=exif_data.get('ShutterSpeedValue'),
                    gps_altitude=exif_data.get('GPSAltitude'),
                    gps_altitude_ref=exif_data.get('GPSAltitudeRef'),
                    gps_latitude=exif_data.get('GPSLatitude'),
                    gps_latitude_ref=exif_data.get('GPSLatitudeRef'),
                    gps_longitude=exif_data.get('GPSLongitude'),
                    gps_longitude_ref=exif_data.get('GPSLongitudeRef'),
                    make=exif_data.get('Make'),
                    model=exif_data.get('Model'),
                    lens_make=exif_data.get('LensMake'),
                    lens_model=exif_data.get('LensModel'),
                    exposure_time_star=exif_data.get('ExposureTime'),
                    f_number_star=exif_data.get('FNumber'),
                    iso_star=exif_data.get('ISOSpeedRatings'),
                    focal_length_star=exif_data.get('FocalLength')
                )
        return super().form_valid(form)


class UpdateView(generic.edit.UpdateView):
    model = Submissions
    fields = '__all__'

    def form_valid(self, form):
        self.object = form.save()
        with Image.open(self.object.image.path) as img:
            exif_data = get_exif_data(img)
            if exif_data is not None:
                Exif.objects.create(
                    submission=self.object,
                    aperture_value=exif_data.get('ApertureValue'),
                    brightness_value=exif_data.get('BrightnessValue'),
                    date_time_original=exif_data.get('DateTimeOriginal'),
                    exposure_bias_value=exif_data.get('ExposureBiasValue'),
                    exposure_program=exif_data.get('ExposureProgram'),
                    exposure_time=exif_data.get('ExposureTime'),
                    f_number=exif_data.get('FNumber'),
                    iso=exif_data.get('ISOSpeedRatings'),
                    max_aperture_value=exif_data.get('MaxApertureValue'),
                    metering_mode=exif_data.get('MeteringMode'),
                    shutter_speed_value=exif_data.get('ShutterSpeedValue'),
                    gps_altitude=exif_data.get('GPSAltitude'),
                    gps_altitude_ref=exif_data.get('GPSAltitudeRef'),
                    gps_latitude=exif_data.get('GPSLatitude'),
                    gps_latitude_ref=exif_data.get('GPSLatitudeRef'),
                    gps_longitude=exif_data.get('GPSLongitude'),
                    gps_longitude_ref=exif_data.get('GPSLongitudeRef'),
                    make=exif_data.get('Make'),
                    model=exif_data.get('Model'),
                    lens_make=exif_data.get('LensMake'),
                    lens_model=exif_data.get('LensModel'),
                    exposure_time_star=exif_data.get('ExposureTime'),
                    f_number_star=exif_data.get('FNumber'),
                    iso_star=exif_data.get('ISOSpeedRatings'),
                    focal_length_star=exif_data.get('FocalLength')
                )
        return super().form_valid(form)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' >
        <style>body {padding-top: 80px;}</style>
        <title>mainapp</title>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "mainapp:index" %}'>mainapp</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

mainapp/templates/mainapp/submissions_confirm_delete.html
{% extends './base.html' %}
{% block content %}

<h1>投稿内容の削除</h1>
<p>'{{ object.username }}'を削除しますか?</p>
<form action='' method='post'>{% csrf_token %}
    <button type='submit' class='submit delete'>削除する</button>
</form>

<div>
    <p><a href='JavaScript:history.back()'>&lt; 戻る</a></p>
</div>

{% endblock %}

mainapp/templates/mainapp/submissions_detail.html
{% extends './base.html' %}
{% block content %}

<h1>{{ submissions.username }}</h1>
<div>
    <p>ユーザー名：{{ submissions.username }}</p>
    <img src="{{ submissions.image.url }}" alt="投稿画像" width="200">
    <p>コメント：{{ submissions.comment }}</p>

    {% if submissions.exif_data %}
        <ul>
            <li>Camera Make: {{ submissions.exif_data.make }}</li>
            <li>Camera Model: {{ submissions.exif_data.model }}</li>
            <li>Aperture Value: {{ submissions.exif_data.aperture_value }}</li>
            <li>Brightness Value: {{ submissions.exif_data.brightness_value }}</li>
            <li>Date Time Original: {{ submissions.exif_data.date_time_original }}</li>
            <li>Exposure Bias Value: {{ submissions.exif_data.exposure_bias_value }}</li>
            <li>Exposure Program: {{ submissions.exif_data.exposure_program }}</li>
            <li>Exposure Time: {{ submissions.exif_data.exposure_time }}</li>
            <li>F Number: {{ submissions.exif_data.f_number }}</li>
            <li>ISO: {{ submissions.exif_data.iso }}</li>
            <li>Max Aperture Value: {{ submissions.exif_data.max_aperture_value }}</li>
            <li>Metering Mode: {{ submissions.exif_data.metering_mode }}</li>
            <li>Shutter Speed Value: {{ submissions.exif_data.shutter_speed_value }}</li>
            <li>GPS Altitude: {{ submissions.exif_data.gps_altitude }}</li>
            <li>GPS Latitude: {{ submissions.exif_data.gps_latitude }}</li>
            <li>GPS Longitude: {{ submissions.exif_data.gps_longitude }}</li>
        </ul>
        <div id="map" style="height: 400px; width: 100%;"></div>
    {% else %}
        <p>No Exif data available for this image.</p>
    {% endif %}
</div>
<div>
    <a href='{% url "mainapp:index" %}'>一覧</a> |
    <a href='{% url "mainapp:update" submissions.pk %}'>編集</a> |
    <a href='{% url "mainapp:delete" submissions.pk %}'>削除</a>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBg3BavEGypj-SHgY-vw80rCbyTeNXbKuI"></script>
<script>
    function initMap() {
        var latitude = {{ submissions.exif_data.gps_latitude }};
        var longitude = {{ submissions.exif_data.gps_longitude }};
        var location = {lat: latitude, lng: longitude};

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 8,
            center: location
        });

        var marker = new google.maps.Marker({
            position: location,
            map: map
        });
    }

    // Initialize the map
    google.maps.event.addDomListener(window, 'load', initMap);
</script>

{% endblock %}

mainapp/templates/mainapp/submissions_form.html
{% extends './base.html' %}
{% block content %}

<h1>投稿内容の{{ object|yesno:'更新,作成'}}</h1>

<form action='' method='post' enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='submit'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

mainapp/templates/mainapp/submissions_list.html
{% extends './base.html' %}
{% block content %}
    <h1>投稿一覧</h1>
    <table class='table table-striped table-hover'>
        {% for submissions in object_list %}
        <tr>
            <td><a href='{% url "mainapp:detail" submissions.pk %}'><p>ユーザー名：{{ submissions.username }}</p></a></td>
            <td><a href='{% url "mainapp:detail" submissions.pk %}'><img src="{{ submissions.image.url }}" alt="投稿画像" width="200"></a></td>
        </tr>
        {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; 最初</a>
                <a href="?page={{ page_obj.previous_page_number }}">前</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">次</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">最後 &raquo;</a>
            {% endif %}
        </span>
    </div>

    <div>
        <a href='{% url "mainapp:create" %}'>新しい投稿</a>
    </div>
{% endblock %}